name: ecitykiosk
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #Functionality Packages
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  http: ^0.13.4
  url_launcher:
  flutter_udid: ^2.0.0
  flutter_svg: ^1.0.3
  location: ^4.4.0
  keyboard_utils: ^1.3.4
#  flutter_inappwebview: ^5.4.3+7
  fluttertoast: ^8.0.9
  firebase_crashlytics: ^2.8.0
  carousel_slider: ^4.1.1
  pin_code_fields: ^7.4.0
  flutter_inappwebview: ^5.4.3+7

  #UI Packages
  flutter_native_splash: ^2.2.1
#  firebase_messaging: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/recent/

  fonts:
    - family: Josefin_Sans
      fonts:
        - asset: assets/fonts/JosefinSans-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/JosefinSans-Light.ttf
          weight: 300
        - asset: assets/fonts/JosefinSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/JosefinSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/JosefinSans-SemiBold.ttf
          weight: 600
    - family: Josefin_Slab
      fonts:
        - asset: assets/fonts/JosefinSlab-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/JosefinSlab-Bold.ttf
          weight: 700

flutter_native_splash:
  color: "#453885"
  image: assets/images/brand.png
  branding: assets/images/brand.png
  fullscreen: true